{application, clubq_api, [
    {vsn, "0.1.0"},
    {applications, [envoy,
                    gleam_erlang,
                    gleam_http,
                    gleam_httpc,
                    gleam_json,
                    gleam_otp,
                    gleam_stdlib,
                    mist,
                    pog,
                    wisp]},
    {description, ""},
    {modules, [clubq_api,
               clubq_api@@main,
               clubq_auth,
               clubq_live,
               clubq_setup,
               clubq_ssl,
               clubq_ssl_ffi,
               clubq_store,
               clubq_uuid]},
    {registered, []}
]}.
